"""Write the demo roster as a generated TypeScript module for the client UI."""

from __future__ import annotations

import json
from pathlib import Path

from scripts.demo_roster import AGENTS, QUEUES


def roster_payload() -> dict[str, object]:
    return {
        "agents": [
            {
                "agent_id": agent.agent_id,
                "agent_name": agent.agent_name,
                "queue_ids": list(agent.queue_ids),
            }
            for agent in AGENTS
        ],
        "queues": sorted(QUEUES),
    }


def main() -> None:
    repo_root = Path(__file__).resolve().parent.parent.parent
    output_path = repo_root / "client" / "src" / "lib" / "generated" / "demo-roster.ts"
    output_path.parent.mkdir(parents=True, exist_ok=True)

    payload = roster_payload()
    agents_json = json.dumps(payload["agents"], indent=2)
    queues_json = json.dumps(payload["queues"], indent=2)

    output_path.write_text(
        "/** Generated by server/scripts/export_demo_roster.py - do not edit. */\n"
        "\n"
        "export interface DemoAgent {\n"
        "  agent_id: string;\n"
        "  agent_name: string;\n"
        "  queue_ids: string[];\n"
        "}\n"
        "\n"
        f"export const DEMO_AGENTS: DemoAgent[] = {agents_json};\n"
        "\n"
        f"export const DEMO_QUEUES: string[] = {queues_json};\n",
        encoding="utf-8",
    )
    print(f"Wrote {output_path}")


if __name__ == "__main__":
    main()
