/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Return a simple liveness probe.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rules */
        get: operations["list_rules_rules_get"];
        put?: never;
        /** Create Rule */
        post: operations["create_rule_rules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rules/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Rule */
        get: operations["get_rule_rules__rule_id__get"];
        put?: never;
        post?: never;
        /** Delete Rule */
        delete: operations["delete_rule_rules__rule_id__delete"];
        options?: never;
        head?: never;
        /** Update Rule */
        patch: operations["update_rule_rules__rule_id__patch"];
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Notifications */
        get: operations["list_notifications_notifications_get"];
        put?: never;
        post?: never;
        /** Clear All */
        delete: operations["clear_all_notifications_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest Event
         * @description Ingest a single domain event and return emitted notification IDs.
         */
        post: operations["ingest_event_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdherenceCheckEvent */
        AdherenceCheckEvent: {
            /** Event Id */
            event_id: string;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "adherence_check";
            /** Agent Id */
            agent_id: string;
            /** Queue Ids */
            queue_ids: string[];
            /** Scheduled State */
            scheduled_state: string;
            /** Actual State */
            actual_state: string;
            /** In Violation */
            in_violation: boolean;
            /** Violation Started At */
            violation_started_at?: string | null;
        };
        /**
         * AgentState
         * @description Workforce agent states used in events and state-duration rules.
         * @enum {string}
         */
        AgentState: "available" | "on_call" | "on_break" | "in_meeting" | "offline";
        /** AgentStateChangeEvent */
        AgentStateChangeEvent: {
            /** Event Id */
            event_id: string;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "agent_state_change";
            /** Agent Id */
            agent_id: string;
            /** Queue Ids */
            queue_ids: string[];
            /** Previous State */
            previous_state: string;
            /** Previous State Duration Sec */
            previous_state_duration_sec: number;
            /** New State */
            new_state: string;
        };
        /**
         * Audience
         * @description Who a rule is intended for in the product UI (not used for routing).
         * @enum {string}
         */
        Audience: "agent" | "team_lead";
        /**
         * ChannelType
         * @description Delivery channels for a notification.
         * @enum {string}
         */
        ChannelType: "console" | "inbox";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Liveness probe response.
         */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /**
         * IngestEventResponse
         * @description Result of evaluating and delivering notifications for one ingested event.
         *
         *     Attributes:
         *         notifications_emitted: Number of notifications created for this event.
         *         notification_ids: Primary keys of those notification rows, in creation order.
         */
        IngestEventResponse: {
            /**
             * Notifications Emitted
             * @description Count of notifications created
             */
            notifications_emitted: number;
            /**
             * Notification Ids
             * @description IDs of created notification rows
             */
            notification_ids: string[];
        };
        /**
         * NotificationRead
         * @description Persisted inbox notification.
         */
        NotificationRead: {
            /** Id */
            id: string;
            /** Rule Id */
            rule_id: string;
            /** Recipient Id */
            recipient_id: string;
            /** Title */
            title: string;
            /** Body */
            body: string;
            severity: components["schemas"]["Severity"];
            /** Entity Key */
            entity_key: string;
            /** Triggering Event Id */
            triggering_event_id: string;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Delivered Channels */
            delivered_channels: components["schemas"]["ChannelType"][];
        };
        /** QueueSnapshotEvent */
        QueueSnapshotEvent: {
            /** Event Id */
            event_id: string;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "queue_snapshot";
            /** Queue Id */
            queue_id: string;
            /** Tickets Waiting */
            tickets_waiting: number;
            /** Longest Wait Sec */
            longest_wait_sec: number;
            /** Sla Target Sec */
            sla_target_sec: number;
            /** Agents Available */
            agents_available: number;
            /** Agents On Call */
            agents_on_call: number;
            /** Volume Last 15M */
            volume_last_15m: number;
            /** Volume Forecast Next 15M */
            volume_forecast_next_15m: number;
        };
        /** RuleCreate */
        RuleCreate: {
            /** Name */
            name: string;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            audience: components["schemas"]["Audience"];
            /** Owner Id */
            owner_id: string;
            scope: components["schemas"]["RuleScope"];
            trigger_type: components["schemas"]["TriggerType"];
            /** Threshold */
            threshold?: number | null;
            target_state?: components["schemas"]["AgentState"] | null;
            /** @default warning */
            severity: components["schemas"]["Severity"];
            /** Channels */
            channels?: components["schemas"]["ChannelType"][];
        };
        /** RuleRead */
        RuleRead: {
            /** Name */
            name: string;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            audience: components["schemas"]["Audience"];
            /** Owner Id */
            owner_id: string;
            scope: components["schemas"]["RuleScope"];
            trigger_type: components["schemas"]["TriggerType"];
            /** Threshold */
            threshold?: number | null;
            target_state?: components["schemas"]["AgentState"] | null;
            /** @default warning */
            severity: components["schemas"]["Severity"];
            /** Channels */
            channels?: components["schemas"]["ChannelType"][];
            /** Id */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Created By */
            created_by: string;
            /** Updated By */
            updated_by: string;
        };
        /** RuleScope */
        RuleScope: {
            /** Agent Id */
            agent_id?: string | null;
            /** Queue Ids */
            queue_ids?: string[] | null;
        };
        /** RuleUpdate */
        RuleUpdate: {
            /** Name */
            name?: string | null;
            /** Enabled */
            enabled?: boolean | null;
            audience?: components["schemas"]["Audience"] | null;
            /** Owner Id */
            owner_id?: string | null;
            scope?: components["schemas"]["RuleScope"] | null;
            trigger_type?: components["schemas"]["TriggerType"] | null;
            /** Threshold */
            threshold?: number | null;
            target_state?: components["schemas"]["AgentState"] | null;
            severity?: components["schemas"]["Severity"] | null;
            /** Channels */
            channels?: components["schemas"]["ChannelType"][] | null;
        };
        /**
         * Severity
         * @description Alert severity copied onto fired notifications.
         * @enum {string}
         */
        Severity: "info" | "warning" | "critical";
        /**
         * TriggerType
         * @description Closed set of rule trigger kinds the evaluator can match.
         * @enum {string}
         */
        TriggerType: "adherence_violation_duration" | "queue_sla_breached" | "queue_tickets_waiting" | "agent_state_duration";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_rules_rules_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Username"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_rule_rules_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Username"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rule_rules__rule_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Username"?: string | null;
            };
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_rule_rules__rule_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-Username"?: string | null;
            };
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_rule_rules__rule_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-Username"?: string | null;
            };
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_notifications_notifications_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationRead"][];
                };
            };
        };
    };
    clear_all_notifications_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ingest_event_events_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueueSnapshotEvent"] | components["schemas"]["AgentStateChangeEvent"] | components["schemas"]["AdherenceCheckEvent"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestEventResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
